"""Self-contained HTML report. The diagram renders through Mermaid when online
and degrades to the diagram source otherwise."""

from __future__ import annotations

from html import escape

from agent_threat_model.catalogue.references import atlas_url
from agent_threat_model.diagram import mermaid
from agent_threat_model.engine import Analysis
from agent_threat_model.reporters.common import (
    agentic_labels,
    band_label,
    owasp_labels,
    stride_title,
    summary_sentence,
)

MERMAID_SRC = "https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.min.js"

STYLE = """
:root { --bg: #ffffff; --fg: #1f2328; --muted: #57606a; --line: #d0d7de; --card: #f6f8fa;
  --critical: #a40e26; --high: #cf222e; --medium: #9a6700; --low: #1a7f37; }
@media (prefers-color-scheme: dark) {
  :root { --bg: #0d1117; --fg: #e6edf3; --muted: #8b949e; --line: #30363d; --card: #161b22;
    --critical: #ff7b72; --high: #f85149; --medium: #d29922; --low: #3fb950; } }
body { margin: 0; padding: 24px 16px; background: var(--bg); color: var(--fg);
  font: 15px/1.5 system-ui, -apple-system, "Segoe UI", sans-serif; }
main { max-width: 1080px; margin: 0 auto; }
h1, h2, h3 { line-height: 1.25; }
table { border-collapse: collapse; width: 100%; margin: 12px 0; font-size: 14px; }
th, td { border: 1px solid var(--line); padding: 6px 8px; text-align: left; vertical-align: top; }
th { background: var(--card); }
code { background: var(--card); padding: 1px 4px; border-radius: 4px; font-size: 13px; }
pre { background: var(--card); padding: 12px; overflow-x: auto; border-radius: 6px; }
.cards { display: flex; flex-wrap: wrap; gap: 12px; margin: 16px 0; }
.card { flex: 1 1 160px; background: var(--card); border: 1px solid var(--line);
  border-radius: 8px; padding: 12px 14px; }
.card .n { font-size: 28px; font-weight: 700; }
.card .l { color: var(--muted); font-size: 13px; }
.band-critical { color: var(--critical); font-weight: 700; }
.band-high { color: var(--high); font-weight: 600; }
.band-medium { color: var(--medium); font-weight: 600; }
.band-low { color: var(--low); font-weight: 600; }
details { border: 1px solid var(--line); border-radius: 8px; padding: 8px 14px; margin: 8px 0; }
summary { cursor: pointer; font-weight: 600; }
ul.check { list-style: none; padding-left: 0; }
ul.check li::before { content: "\\2610  "; }
ul.check li.present::before { content: "\\2611  "; }
.muted { color: var(--muted); }
"""


def _band(band: str) -> str:
    return f'<span class="band-{band}">{escape(band_label(band))}</span>'


def render_html(analysis: Analysis) -> str:
    system = analysis.system
    counts = analysis.band_counts()
    e = escape
    out: list[str] = []
    out.append("<!doctype html>")
    out.append('<html lang="en"><head><meta charset="utf-8">')
    out.append('<meta name="viewport" content="width=device-width, initial-scale=1">')
    out.append(f"<title>Threat model: {e(system.system.name)}</title>")
    out.append(f"<style>{STYLE}</style></head><body><main>")
    out.append(f"<h1>Threat model: {e(system.system.name)}</h1>")
    out.append(
        f'<p class="muted">Generated by agent-threat-model {e(analysis.tool_version)} '
        f"from <code>{e(analysis.source)}</code>. Deterministic, no model in the loop.</p>"
    )
    if system.system.description:
        out.append(f"<p>{e(system.system.description.strip())}</p>")

    out.append("<h2>Executive summary</h2>")
    out.append('<div class="cards">')
    out.append(
        f'<div class="card"><div class="n">{analysis.residual_risk_score}<span class="l">/100'
        f'</span></div><div class="l">Residual risk, {e(band_label(analysis.rating))}</div></div>'
    )
    out.append(
        f'<div class="card"><div class="n">{len(analysis.findings)}</div>'
        '<div class="l">Applicable threats</div></div>'
    )
    for band in ("critical", "high", "medium", "low"):
        out.append(
            f'<div class="card"><div class="n band-{band}">{counts[band]}</div>'
            f'<div class="l">{e(band_label(band))} (residual)</div></div>'
        )
    out.append("</div>")
    out.append(f"<p>{e(summary_sentence(analysis))}</p>")

    out.append("<h2>System diagram</h2>")
    out.append(
        '<p class="muted">Dashed edges are trusted channels; solid red edges are untrusted '
        "channels.</p>"
    )
    out.append(f'<pre class="mermaid">{e(mermaid(system))}</pre>')

    out.append("<h2>Threat register</h2>")
    out.append(
        "<table><thead><tr><th>#</th><th>Threat</th><th>STRIDE</th><th>OWASP LLM</th>"
        "<th>Inherent</th><th>Residual</th><th>Affected</th></tr></thead><tbody>"
    )
    for rank, f in enumerate(analysis.findings, start=1):
        out.append(
            f'<tr><td>{rank}</td><td><a href="#t-{e(f.threat_id)}">{e(f.title)}</a></td>'
            f"<td>{e(stride_title(f.stride))}</td><td>{e(', '.join(f.owasp_llm) or '-')}</td>"
            f"<td>{f.inherent} {_band(f.inherent_band)}</td>"
            f"<td>{f.residual:g} {_band(f.residual_band)}</td>"
            f"<td>{' '.join(f'<code>{e(x)}</code>' for x in f.elements)}</td></tr>"
        )
    out.append("</tbody></table>")

    for rank, f in enumerate(analysis.findings, start=1):
        out.append(
            f'<details id="t-{e(f.threat_id)}"><summary>{rank}. {e(f.title)} '
            f"({_band(f.residual_band)}, residual {f.residual:g})</summary>"
        )
        out.append(f"<p>{e(f.description)}</p>")
        atlas = ", ".join(f'<a href="{e(atlas_url(i))}">{e(i)}</a>' for i in f.mitre_atlas) or "-"
        out.append("<table><tbody>")
        out.append(f"<tr><th>STRIDE</th><td>{e(stride_title(f.stride))}</td></tr>")
        owasp = e(", ".join(owasp_labels(f.owasp_llm)) or "-")
        out.append(f"<tr><th>OWASP LLM Top 10 (2025)</th><td>{owasp}</td></tr>")
        agentic = e(", ".join(agentic_labels(f.owasp_agentic)) or "not mapped")
        out.append(f"<tr><th>OWASP Agentic Top 10 (2026)</th><td>{agentic}</td></tr>")
        out.append(f"<tr><th>MITRE ATLAS</th><td>{atlas}</td></tr>")
        out.append(
            f"<tr><th>Severity</th><td>inherent {f.inherent} ({_band(f.inherent_band)}), "
            f"residual {f.residual:g} ({_band(f.residual_band)}), coverage "
            f"{round(f.coverage * 100)}%</td></tr>"
        )
        out.append(f"<tr><th>Rule</th><td><code>{e(f.rule)}</code></td></tr>")
        out.append("</tbody></table>")
        out.append("<p>Why it applies:</p><ul>")
        out.extend(f"<li>{e(r)}</li>" for r in f.reasons)
        out.append('</ul><p>Mitigations:</p><ul class="check">')
        out.extend(f'<li class="present"><code>{e(c)}</code></li>' for c in f.mitigations_present)
        out.extend(f"<li><code>{e(c)}</code></li>" for c in f.mitigations_missing)
        out.append("</ul></details>")

    out.append("<h2>Control checklist</h2>")
    for effort, heading in (
        ("low", "Low effort"),
        ("medium", "Medium effort"),
        ("high", "High effort"),
    ):
        group = [c for c in analysis.controls if c.effort == effort]
        if not group:
            continue
        out.append(f'<h3>{heading}</h3><ul class="check">')
        for c in sorted(group, key=lambda c: (c.present, -len(c.threats), c.id)):
            cls = ' class="present"' if c.present else ""
            threats = ", ".join(c.threats) or "no applicable threat"
            out.append(
                f'<li{cls}><code>{e(c.id)}</code> {e(c.title)} <span class="muted">'
                f"({e(c.type)}; {e(threats)})</span></li>"
            )
        out.append("</ul>")

    out.append("<h2>Residual risk</h2>")
    out.append(
        f"<p><strong>Residual risk score {analysis.residual_risk_score}/100 "
        f"({_band(analysis.rating)})</strong>. Inherent total {analysis.inherent_total:g}, "
        f"residual total {analysis.residual_total:g}, baseline with no controls "
        f"{analysis.baseline_total:g}. Declared controls remove {analysis.reduction_percent}% "
        "of modelled risk.</p>"
    )
    out.append(
        '<p class="muted">Per threat: inherent = likelihood x impact; residual = inherent x '
        "(1 - 0.8 x coverage) where coverage weights controls in place by type.</p>"
    )
    out.append(
        f'<script type="module">import mermaid from "{MERMAID_SRC}";'
        "mermaid.initialize({ startOnLoad: true, securityLevel: 'strict' });</script>"
    )
    out.append("</main></body></html>")
    return "\n".join(out) + "\n"
