"""Markdown report with executive summary, diagram, register, checklist and residual risk."""

from __future__ import annotations

from agent_threat_model.catalogue.references import atlas_url
from agent_threat_model.diagram import mermaid
from agent_threat_model.engine import Analysis, Finding
from agent_threat_model.reporters.common import (
    agentic_labels,
    band_label,
    owasp_labels,
    stride_title,
    summary_sentence,
    top_missing_controls,
)

EFFORT_SECTIONS = (("low", "Low effort"), ("medium", "Medium effort"), ("high", "High effort"))


def _finding_section(rank: int, finding: Finding, analysis: Analysis) -> list[str]:
    lines = [f"### {rank}. {finding.title} (`{finding.threat_id}`)", ""]
    lines.append(finding.description)
    lines.append("")
    lines.append("| Field | Value |")
    lines.append("|---|---|")
    lines.append(f"| STRIDE | {stride_title(finding.stride)} |")
    lines.append(
        f"| OWASP LLM Top 10 (2025) | {', '.join(owasp_labels(finding.owasp_llm)) or '-'} |"
    )
    agentic = ", ".join(agentic_labels(finding.owasp_agentic)) or "not mapped"
    lines.append(f"| OWASP Agentic Top 10 (2026) | {agentic} |")
    atlas = ", ".join(f"[{i}]({atlas_url(i)})" for i in finding.mitre_atlas) or "-"
    lines.append(f"| MITRE ATLAS | {atlas} |")
    adjusted = " (impact raised: regulated data in scope)" if finding.impact_adjusted else ""
    lines.append(
        f"| Inherent severity | {finding.inherent} ({band_label(finding.inherent_band)}): "
        f"likelihood {finding.likelihood} x impact {finding.impact}{adjusted} |"
    )
    lines.append(
        f"| Residual severity | {finding.residual:g} ({band_label(finding.residual_band)}), "
        f"mitigation coverage {round(finding.coverage * 100)}% |"
    )
    lines.append(f"| Affected elements | {', '.join(f'`{e}`' for e in finding.elements) or '-'} |")
    lines.append(f"| Rule | `{finding.rule}` |")
    lines.append("")
    lines.append("Why it applies:")
    lines.append("")
    lines.extend(f"- {reason}" for reason in finding.reasons)
    lines.append("")
    lines.append("Mitigations:")
    lines.append("")
    for control_id in finding.mitigations_present:
        lines.append(f"- [x] `{control_id}` {_control_title(analysis, control_id)}")
    for control_id in finding.mitigations_missing:
        lines.append(f"- [ ] `{control_id}` {_control_title(analysis, control_id)}")
    if finding.references:
        lines.append("")
        lines.append("References:")
        lines.append("")
        lines.extend(f"- <{ref}>" for ref in finding.references)
    lines.append("")
    return lines


def _control_title(analysis: Analysis, control_id: str) -> str:
    for control in analysis.controls:
        if control.id == control_id:
            return control.title
    return ""


def render_markdown(analysis: Analysis) -> str:
    system = analysis.system
    counts = analysis.band_counts()
    inherent_counts = analysis.band_counts(residual=False)
    lines: list[str] = []
    lines.append(f"# Threat model: {system.system.name}")
    lines.append("")
    lines.append(
        f"Generated by agent-threat-model {analysis.tool_version} from `{analysis.source}`. "
        "Deterministic output: the same input always produces this report."
    )
    lines.append("")
    if system.system.description:
        lines.append(system.system.description.strip())
        lines.append("")
    if system.system.owner:
        lines.append(f"Owner: {system.system.owner}")
        lines.append("")

    lines.append("## Executive summary")
    lines.append("")
    lines.append(summary_sentence(analysis))
    lines.append("")
    lines.append("| Severity | Inherent | Residual |")
    lines.append("|---|---|---|")
    for band in ("critical", "high", "medium", "low"):
        lines.append(f"| {band_label(band)} | {inherent_counts[band]} | {counts[band]} |")
    lines.append("")
    if analysis.findings:
        lines.append("Top threats after mitigations:")
        lines.append("")
        for finding in analysis.findings[:3]:
            lines.append(
                f"1. **{finding.title}** (`{finding.threat_id}`), residual {finding.residual:g} "
                f"{band_label(finding.residual_band)}: {finding.reasons[0]}"
            )
        lines.append("")
    missing = top_missing_controls(analysis)
    if missing:
        lines.append("Highest-leverage missing controls:")
        lines.append("")
        for control_id, title, count in missing:
            lines.append(f"- `{control_id}` {title}: mitigates {count} applicable threat(s)")
        lines.append("")

    lines.append("## System diagram")
    lines.append("")
    lines.append(
        "Dashed edges are trusted channels; solid red edges are untrusted channels "
        "(attacker-influenced content reaches the agent)."
    )
    lines.append("")
    lines.append("```mermaid")
    lines.append(mermaid(system).rstrip())
    lines.append("```")
    lines.append("")

    lines.append("## System overview")
    lines.append("")
    lines.append("| Element | Id | Details |")
    lines.append("|---|---|---|")
    for p in system.principals:
        lines.append(f"| Principal | `{p.id}` | {p.kind.value}, trust {p.trust.value} |")
    for a in system.agents:
        lines.append(
            f"| Agent | `{a.id}` | autonomy {a.autonomy.value}, memory {a.memory.value}, "
            f"inputs {len(a.inputs)}, tools {len(a.tools)}"
            f"{', model pinned' if a.model_pinned else ''} |"
        )
    for c in system.channels:
        trust = "trusted" if c.trusted else "untrusted"
        lines.append(f"| Channel | `{c.id}` | {c.kind.value}, origin {c.origin.value}, {trust} |")
    for t in system.tools:
        extras = [f"auth {t.auth.value}", f"approval {t.approval.value}"]
        if t.sandboxed:
            extras.append("sandboxed")
        if t.provider.value == "third-party":
            extras.append("third-party")
        if t.pinned:
            extras.append("pinned")
        lines.append(f"| Tool | `{t.id}` | {t.kind.value}, {', '.join(extras)} |")
    for s in system.data_stores:
        lines.append(f"| Data store | `{s.id}` | {s.sensitivity.value} |")
    lines.append("")

    lines.append("## Threat register")
    lines.append("")
    if not analysis.findings:
        lines.append("No catalogue threat applies to this system.")
        lines.append("")
    else:
        lines.append("| # | Threat | STRIDE | OWASP LLM | Inherent | Residual | Affected |")
        lines.append("|---|---|---|---|---|---|---|")
        for rank, f in enumerate(analysis.findings, start=1):
            lines.append(
                f"| {rank} | [{f.title}](#{rank}-{_anchor(f.title)}-{f.threat_id}) | "
                f"{stride_title(f.stride)} | {', '.join(f.owasp_llm) or '-'} | "
                f"{f.inherent} {band_label(f.inherent_band)} | "
                f"{f.residual:g} {band_label(f.residual_band)} | "
                f"{', '.join(f'`{e}`' for e in f.elements)} |"
            )
        lines.append("")
        for rank, finding in enumerate(analysis.findings, start=1):
            lines.extend(_finding_section(rank, finding, analysis))

    lines.append("## Control checklist")
    lines.append("")
    lines.append(
        "Controls that mitigate at least one applicable threat, grouped by implementation "
        "effort. Checked items are already declared in the system description."
    )
    lines.append("")
    for effort, heading in EFFORT_SECTIONS:
        group = [c for c in analysis.controls if c.effort == effort]
        if not group:
            continue
        lines.append(f"### {heading}")
        lines.append("")
        for control in sorted(group, key=lambda c: (c.present, -len(c.threats), c.id)):
            mark = "x" if control.present else " "
            threats = ", ".join(f"`{t}`" for t in control.threats) or "no applicable threat"
            lines.append(f"- [{mark}] `{control.id}` {control.title} ({control.type}); {threats}")
        lines.append("")

    lines.append("## Residual risk")
    lines.append("")
    lines.append(
        f"**Residual risk score: {analysis.residual_risk_score}/100 "
        f"({band_label(analysis.rating)})**"
    )
    lines.append("")
    lines.append(f"- Inherent severity total for applicable threats: {analysis.inherent_total:g}")
    lines.append(f"- Residual severity total after declared controls: {analysis.residual_total:g}")
    lines.append(
        f"- Inherent total with no controls at all (baseline): {analysis.baseline_total:g}"
    )
    lines.append(
        f"- Score = 100 x residual / baseline = {analysis.residual_risk_score}; "
        f"declared controls remove {analysis.reduction_percent}% of modelled risk"
    )
    lines.append("")
    lines.append(
        "Per threat: inherent = likelihood x impact (1..25); impact is raised by one when a "
        "regulated data store is affected; residual = inherent x (1 - 0.8 x coverage), where "
        "coverage weights controls in place by type (preventive 1.0, detective 0.6, "
        "corrective 0.5). A fully mitigated threat keeps 20% of its inherent score."
    )
    lines.append("")
    lines.append("## Method and limits")
    lines.append("")
    lines.append(
        "This report is produced by deterministic rules over the declared architecture, "
        "with no model in the loop. It cannot see implementation detail, so a threat that "
        "does not apply here may still exist in code, and a declared control is taken at face "
        "value. Treat it as a starting checklist for a review, not as a verdict."
    )
    lines.append("")
    return "\n".join(lines)


def _anchor(title: str) -> str:
    keep = [ch.lower() if ch.isalnum() else "-" for ch in title.replace(" ", "-")]
    text = "".join(keep)
    while "--" in text:
        text = text.replace("--", "-")
    return text.strip("-")
